<?php


namespace Dreamabout\PHPConomic\Exception;


use Exception;

class AuthenticationException extends PHPConomicException
{
    public function __construct($message = "", $code = 0, Exception $previous = null)
    {
        parent::__construct($message, $code, $previous); // TODO: Change the autogenerated stub
    }

}
